from undyingkingdoms.models.technologies.helpers import generate_tech_levels
from undyingkingdoms.models.technologies import Technology
from undyingkingdoms.models.effects import PlequalsEffect

generic_technology = [
    Technology(
        name='Agriculture',
        cost=500,
        max_level=2,
        description="{grain_modifier:+0.0%} bonus to all grain production within your county.",
        effects=PlequalsEffect(grain_modifier=0.25)
    ),
    Technology(
        name='Animal Husbandry',
        cost=500,
        max_level=1,
        description='{dairy_modifier:+0.0%} bonus to all dairy production within your county.',
        effects=PlequalsEffect(dairy_modifier=0.5)
    ),
    Technology(
        name='Steel',
        cost=1000,
        max_level=1,
        description='{offensive_modifier:+0.0%} Attack Power bonus to all offensive invasions you perform.',
        effects=PlequalsEffect(offensive_modifier=0.1)
    ),
    Technology(
        name='Engineering',
        cost=250,
        max_level=3,
        description='+{build_slots} building can be built each day for each level.',
        effects=PlequalsEffect(build_slots=1)
    ),
    Technology(
        name='Logistics',
        cost=500,
        max_level=1,
        description='Your armies return from battle {speed} day sooner.',
        effects=PlequalsEffect(speed=1)
    ),
    Technology(
        name='Public Works',
        cost=1000,
        max_level=1,
        description='Your county generates an additional +{happiness_change} happiness each day.',
        effects=PlequalsEffect(happiness_change=1)
    ),
    Technology(
        name='Arcane Knowledge',
        cost=500,
        max_level=5,
        description='Each level raises your maximum mana by {max_mana}.',
        effects=PlequalsEffect(max_mana=20)
    ),
    Technology(
        name='Winds of Magic',
        cost=1250,
        max_level=2,
        description='Each level raises your mana generation per day by {mana_change}.',
        effects=PlequalsEffect(mana_change=1),
    ),
]

custom_requirements = {
    'public works': ['engineering']
}

generic_technology, generic_requirements = generate_tech_levels(generic_technology, custom_requirements)

# for tech in generic_technology.values():
#     print(tech.description)


# randomly generated by fake.requirements() as an example
"""
generic_requirements = {
    'agriculture II': ['public works III'],
    'agriculture IV': ['logistics IV', 'engineering IV'],
    'animal husbandry I': ['logistics I'],
    'animal husbandry II': ['logistics II'],
    'animal husbandry III': ['logistics III'],
    'arcane knowledge I': ['logistics I', 'engineering I'],
    'engineering I': ['logistics I'],
    'engineering II': ['steel II'],
    'engineering IV': ['public works IV'],
    'logistics I': ['animal husbandry I'],
    'logistics II': ['agriculture II'],
    'logistics III': ['animal husbandry III', 'public works III'],
    'logistics IV': ['engineering IV', 'arcane knowledge IV'],
    'logistics V': ['public works V', 'steel V'],
    'public works': ['arcane knowledge'],
    'public works III': ['agriculture III', 'logistics III'],
    'public works IV': ['animal husbandry IV'],
    'public works V': ['logistics V'],
    'steel': ['engineering'],
    'steel II': ['animal husbandry II', 'logistics II'],
    'steel III': ['public works III', 'animal husbandry III']
}
"""
