from undyingkingdoms.models.magic import Magic

generic_spells = {'instant_happiness': Magic(name='instant_happiness',
                                             display_name='Inspire',
                                             category='instant',
                                             targets='self',
                                             known=True,
                                             mana_cost=25,
                                             output=5,
                                             description='Adds +5 happiness to your county.'),
                  'summon golem': Magic(name='summon golem',
                                             display_name='golem',
                                        category='instant',
                                        targets='self',
                                        known=True,
                                        mana_cost=50,
                                        description='Summon a golem to join your army (Not yet implemented).'),
                  'raise_death_rate': Magic(name='raise_death_rate',
                                             display_name='raise_death_rate',
                                            category='timed',
                                            targets='hostile',
                                            known=True,
                                            mana_cost=30,
                                            duration=12,
                                            description='Adds a disease to an enemy county for 12 days. While diseased,'
                                                        'their people die 50% more quickly.'),
                  'raise_grain_rate': Magic(name='raise_grain_rate',
                                             display_name='raise_grain_rate',
                                            category='aura',
                                            targets='friendly',
                                            known=True,
                                            mana_cost=35,
                                            mana_sustain=2,
                                            description='Pastures produce +50% grain while this spell is in effect.'),
                  'raise_magic_disrupt': Magic(name='raise_magic_disrupt',
                                             display_name='raise_magic_disrupt',
                                               category='aura',
                                               targets='self',
                                               known=True,
                                               mana_cost=20,
                                               mana_sustain=2,
                                               description='While active, enemy spell have an extra 60% chance of failing.')
                  }
