from undyingkingdoms.models.technologies import Technology

generic_technology = {'agriculture': Technology(name='agriculture',
                                                required=750,
                                                tier=1,
                                                max_level=1,
                                                description='+50% bonus to all grain production within your county.'),
                      'animal husbandry': Technology(name='animal husbandry',
                                                     required=750,
                                                     tier=1,
                                                     max_level=1,
                                                     description='+50% bonus to all dairy production within your county.'),
                      'steel': Technology(name='steel',
                                          required=1250,
                                          tier=2,
                                          max_level=1,
                                          description='+10% Attack Power bonus to all offensive invasions you perform.'),
                      'engineering': Technology(name='engineering',
                                                required=250,
                                                tier=1,
                                                max_level=1,
                                                description='+1 building can be built each day.'),
                      'logistics': Technology(name='logistics',
                                              required=500,
                                              tier=1,
                                              max_level=1,
                                              description='Your armies return from battle one day sooner.'),
                      'public works': Technology(name='public works',
                                                 required=750,
                                                 tier=2,
                                                 max_level=1,
                                                 description='Your county generates an additional 1 happiness each day.')
                      }
